name: Publish website

on:
  push:
    branches:
      - source
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: publish-website
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build site
        run: bash ./docker-jekyll.sh compile

      - name: Publish site
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master
          folder: _site
          clean: true
